version: '3'

services:
  db:
    image: mysql/mysql-server
    environment:
        MYSQL_ROOT_PASSWORD: 'jd07gm09'
        MYSQL_ROOT_HOST: '172.19.0.3'
        MYSQL_DATABASE: 'risky'
        MYSQL_USER: 'risky'
        MYSQL_PASSWORD: 'jd07gm09'
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/risky
    ports:
      - "8000:8000"
    depends_on:
      - db
